api spec
vulpemventures/ocean pull request #1
Opened 2021-12-28 12:20 UTC by sekulicd

This adds api spec of the wallet daemon.
Purpose of a daemon is to run as a sidecar for other applications and removes 'heavy burden' of maintaining internal wallet.
Protobuf files are splitted into 4 files that I see as main features of the wallet.
Wallet -> covers creation/restore of wallet
Account -> covers creation on addresses, tracking balance and uspents for specific account
Transaction -> used for crafting various types of transactions
Notification  -> defines rpc's that are to be used for fetching notification.

@tiero @altafan please review.

2021-12-28 12:56 UTC, tiero commented on Makefile
> +proto:
shall we start with buf.build?

2021-12-28 12:58 UTC, tiero commented on api-spec/protobuf/account.proto
> +message UpdateRequest{
This is only to update the `name`? not changes to derivations?

2021-12-28 12:58 UTC, tiero commented on api-spec/protobuf/account.proto
> +message UpdateRequest{
better to specify in the comment then (since we generate doc from it)

2021-12-28 13:17 UTC, tiero commented on api-spec/protobuf/account.proto
> +  bytes value = 4;
I prefer to have a dedicate field for each, when blinded we leave this empty, when unblinded we should return both.

2021-12-28 13:18 UTC, tiero commented on api-spec/protobuf/account.proto
> +    RANDOM = 0;
```suggestion
    BRANCH_BOUND = 0;
    FRAGMENT =1;
    
```

the onw

2021-12-28 15:36 UTC, tiero commented on api-spec/protobuf/notification.proto
> +  bytes value = 4;
same here

2021-12-28 15:38 UTC, tiero commented
Just to keep in mind, Conceptually we can load the wallet also in a watch-only mode ie. no signing keys on board, only xpub(s) and master blinding key.

Maybe an RPC in Wallet service that gives us this info could be helpful

2021-12-28 15:39 UTC, tiero commented on api-spec/protobuf/wallet.proto
> +  rpc Open (OpenRequest) returns (OpenResponse);
```suggestion
  rpc Unlock (OpenRequest) returns (OpenResponse);
```

2021-12-28 17:02 UTC, tiero commented on api-spec/protobuf/wallet.proto
> +}
we should specify the derivation path here

2021-12-29 14:50 UTC, sekulicd commented on api-spec/protobuf/wallet.proto
> +}
what about descriptor?

2021-12-29 15:02 UTC, sekulicd commented on api-spec/protobuf/wallet.proto
> +  rpc Open (OpenRequest) returns (OpenResponse);
Done

2021-12-29 15:02 UTC, sekulicd commented on api-spec/protobuf/notification.proto
> +  bytes value = 4;
Done

2021-12-29 15:02 UTC, sekulicd commented on api-spec/protobuf/account.proto
> +    RANDOM = 0;
Done

2021-12-29 15:02 UTC, sekulicd commented on api-spec/protobuf/account.proto
> +  bytes value = 4;
Done

2021-12-29 15:02 UTC, sekulicd commented on api-spec/protobuf/account.proto
> +message UpdateRequest{
Done__

2021-12-29 16:45 UTC, tiero commented on api-spec/protobuf/wallet.proto
> +}
I do think should instead be under Account, and be a dedicate RPC: ideally CreateAccount derives new xpub, with that result we pass it to compose our descriptor/miniscript/ionio in a second `UpdateScriptTemplate` kind of.

2021-12-30 16:10 UTC, tiero commented on api-spec/protobuf/account.proto
> +  int64 account_index = 1;
Add the resulting xpub for the account here

2021-12-30 16:12 UTC, tiero commented on api-spec/protobuf/account.proto
> +}
Add here a `template` field, to accept descriptor, miniscript, ionio, raw opcode templates etc..

2021-12-30 16:15 UTC, tiero commented on api-spec/protobuf/account.proto
> +  Type type = 3;
replace `Type` with template field

2021-12-30 16:18 UTC, tiero commented on api-spec/protobuf/types.proto
> +
```protobuf
message Template {
  enum Format {
    DESCRIPTOR = 0,
    MINISCRIPT = 1,
    IONIO = 2,
    RAW =3
  }
  Format format = 1;
  string value;
}
```

2021-12-30 18:44 UTC, altafan requested changes
CreatePsbt, Mint, ReMint, Burn, Transfer and ClaimPegin, they all suppose the service to use or select utxos to be used as inputs of a transaction.

Shall all these utxos be marked as locked until the tx is not detected as broadcasted or unconfirmed to prevent the wallet from using them for other requests in the meantime?

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/notification.proto
> +  string tx_id = 1;
would also add a field for the status of the transaction. Could be of type `TxEventType`.

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/notification.proto
> +  }
```suggestion
  enum TxEventType {
    // tx broadcasted
    BROADCASTED = 0;
    //tx unconfirmed
    UNCONFIRMED = 1;
    //tx confirmed
    CONFIRMED = 2;
  }
```

The UNCONFIRMED status is needed because it reflects the tx being in mempool, waiting to be included in blockchain.

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/notification.proto
> +  // Id of the account for which we want to track unspents, either name or id needs to be provided.
```suggestion
  // Name of the account for which we tracking unspents, either name or id needs to be provided.
```

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/notification.proto
> +  // Id of the account for which we want to track unspents, either id or name needs to be provided.
```suggestion
  // Id of the account for which tracking unspents, either id or name needs to be provided.
```

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/notification.proto
> +}
I would use TxEventType as the list of events that a webhook can subscribe to.
Not sure unspents-related events should be subscribable.

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/transaction.proto
> +  string tx = 1;
```suggestion
  // signed tx in hex format
  string tx_hex = 1;
```

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/transaction.proto
> +  rpc UpdateFee (UpdateFeeRequest) returns (UpdateFeeResponse);
Having only UpdateFee to set a custom sats/byte ratio might turn to be unconfortable.
Why not have an optional `sats_per_byte` field in CreatePsbt, Mint, ReMint, Burn, Transfer and ClaimPegin to dynamically set this ratio?

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/transaction.proto
> +  // transaction hex to be broadcast
```suggestion
  // transaction hex to be broadcasted
```

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/transaction.proto
> +  // inputs(unspents) to be spent from, if no inputs are provided, daemon will select it
```suggestion
  // unspents to spend to cover output amount. If no inputs are provided, they will be selected
```

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/account.proto
> +  int64 account_index = 1;
Also the derivation path of the xpub for completeness?

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/account.proto
> +message AccountInfo {
missing xpub and derivation path?

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/types.proto
> +message Unspent {
missing field for status (un)confirmed

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/types.proto
> +  bytes script = 7;
would also add a string field for the address to easily get the related singing/blinding info if needed.

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/account.proto
> +  map<string, Unspents> unspents = 1;
Maybe grouping unspents based on their (un)confirmed status would make more sense?

What about those unspents used for example in a not yet broadcasted Mint tx (ins are automatically selected by the service)?
Should they be recognized as "locked"?
If yes, should they be returned here?
If yes, then we should group all unspents based on their (un)confirmed or locked status.

2021-12-30 18:44 UTC, altafan commented on api-spec/protobuf/types.proto
> +message Unspent {
maybe missing a field for status (un)locked?

2021-12-31 11:39 UTC, sekulicd commented on api-spec/protobuf/types.proto
> +
Done

2021-12-31 11:39 UTC, sekulicd commented on api-spec/protobuf/account.proto
> +}
Done

2021-12-31 11:39 UTC, sekulicd commented on api-spec/protobuf/account.proto
> +  int64 account_index = 1;
Done

2021-12-31 11:40 UTC, sekulicd commented on api-spec/protobuf/account.proto
> +  Type type = 3;
Done

2021-12-31 11:41 UTC, sekulicd commented on api-spec/protobuf/wallet.proto
> +  rpc Seed(SeedRequest) returns (SeedReply);
Done

2021-12-31 11:41 UTC, sekulicd commented on api-spec/protobuf/wallet.proto
> +  string blinding_mnemonic = 2;
Done

2021-12-31 11:42 UTC, sekulicd commented on api-spec/protobuf/wallet.proto
> +  rpc CreateWallet(CreateWalletRequest) returns (CreateWalletResponse);
Done

2021-12-31 11:43 UTC, sekulicd commented on api-spec/protobuf/wallet.proto
> +  rpc Restore (RestoreRequest) returns (RestoreResponse);
Done

2021-12-31 11:43 UTC, sekulicd commented on api-spec/protobuf/types.proto
> +  string tx_id = 1;
Done

2021-12-31 11:44 UTC, sekulicd commented on api-spec/protobuf/transaction.proto
> +  string prevout_tx_id = 1;
Done

2021-12-31 11:47 UTC, sekulicd commented on api-spec/protobuf/transaction.proto
> +  int64 amount = 2;
Done

2021-12-31 11:49 UTC, sekulicd commented on api-spec/protobuf/transaction.proto
> +  string tx = 1;
Done

2021-12-31 11:49 UTC, sekulicd commented on api-spec/protobuf/transaction.proto
> +  string tx = 1;
Done

2021-12-31 11:49 UTC, sekulicd commented on api-spec/protobuf/transaction.proto
> +  string tx = 1;
Done

2021-12-31 11:49 UTC, sekulicd commented on api-spec/protobuf/transaction.proto
> +  string tx = 1;
Done

2021-12-31 11:51 UTC, sekulicd commented on api-spec/protobuf/notification.proto
> +  }
Done

2021-12-31 11:53 UTC, sekulicd commented on api-spec/protobuf/notification.proto
> +  // Id of the account for which we want to track unspents, either name or id needs to be provided.
Done

2021-12-31 11:54 UTC, sekulicd commented on api-spec/protobuf/transaction.proto
> +  string tx = 1;
Done

2021-12-31 11:54 UTC, sekulicd commented on api-spec/protobuf/transaction.proto
> +  // transaction hex to be broadcast
Done

2021-12-31 11:56 UTC, sekulicd commented on api-spec/protobuf/notification.proto
> +}
What about tdex-daemon which would like to follow balance for eg?

2021-12-31 11:57 UTC, sekulicd commented on api-spec/protobuf/transaction.proto
> +  rpc UpdateFee (UpdateFeeRequest) returns (UpdateFeeResponse);
I think fee should not change so freq and u do it once (from time to time) for all calls.
@tiero what do u think ?

2021-12-31 13:13 UTC, sekulicd commented on api-spec/protobuf/transaction.proto
> +  // inputs(unspents) to be spent from, if no inputs are provided, daemon will select it
Done

2021-12-31 13:14 UTC, sekulicd commented on api-spec/protobuf/account.proto
> +message AccountInfo {
Done

2021-12-31 13:49 UTC, closed without merging