Single-key native segwit Ocean wallet implementation
vulpemventures/ocean pull request #11
Opened 2022-03-21 15:33 UTC by altafan

This adds the very first version of the Ocean implementation of a single-key native-segwit wallet.

## Design 

The following is a representation of the project design as a bullet list from the inner layer  to the outer:

- **Domain layer**: the core domains are essentially a copycat of those of tdex-daemon. Domain repositories generate events for real-time updates on the internal status of wallet and relates accounts/utxos/txs:
    * `Wallet/Account` to handle lock/unlock, key pairs derivation, etc, and related Repo.
    * `Utxo` representing an output owned by one of the accounts of the wallet, and related Repo. Utxos are all stored as revealed.
    * `Transaction` representing a tx involving one or more wallet accounts, and related Repo (this was not present in tdex-daemon). 
- **Application layer**: core services reflecting the proto of the api-spec. These services make use of external ones, "hided" behind "portable interfaces" to avoid lock-in dependencies in the core business logic:
    * `WalletService` -  TODO: Restore.
    * `AccountService` - complete.
    * `TransactionService` - TODO: Mint, Remint, Burn, Pegin, ClaimPegin.
    * `NotificationService` - complete.
- **Ports layer**: a collection of services defined as interfaces used at application level:
    * `RepoManager` - handles connection with concrete db and allows to register handlers for domain events.
    * `BlockchainScanner` - a sort of revised tdex-daemon's blockchain listener. A service listening to blockchain/mempool events and notifying the wallet about utxos/txs related to addresses of its accounts.
    * `MnemonicStore` - the place where to persist the wallet mnemonic in plain text
    * `MnemonicCypher` - a service that encrypts/decrypts a text using a password.
    * `CoinSelector` - a service that implements a specific coin selection strategy and returns a subset of the give utxos covering target amount and asset.
- Infrastructure (implementation) layer: this is not a proper layer but rather a collection of implementations of the core portable interfaces:
    * `RepoManager` - inmemory and badger implementations.
    * `BlockchainScanner` - neutrino implementation.
    * `MnemonicStore` - inmemory implementation (makes us of viper).
    * `MnemonicCypher` - AES128 implementation.
    * `CoinSelector` - smallest subset strategy impl (already implemented in tdex-daemon).
- **Interface layer**:
    *  gRPC, with or without TLS enabled. Let's consider adding: macaroon auth, grpc gateway. For both topics, we will eventually open dedicated tickets if we want them as features of the grpc interface.

## Flow

The list below is a description of the flows generated by domain events:

- *Unlocking the wallet*: The grpc service start with only its WalletService registered on the public reachable interface and registers a handler to get notified whenever the wallet is unlocked. When this happens, the service registers the missing service to the public interface.
- *Creating an account*: When a new account is created, ocean spawns a dedicated blockchain scanner for that account, which is stopped only if the account is deleted or the wallet switched off. At wallet restart, ocean takes care of spawning a bc scanner for every existing account and start watching all its derived addresses.
- *Deriving a new address*: A new account address can be derived by either the user or the wallet itself (change address, when crafting a tx).  Whenever one or more addresses are derived, those are passed to the account's bc scanner in order to start watching them and get eventually notified about related utxos/txs. When a tx report is received, the tx itself and the utxos owned by the wallet are stored in the related repositories.
- *Selecting utxos*: When asking the wallet to select utxos for a target amount and asset, those returned in response are temporarily locked by the system to prevent double-spending them in other txs. Whenever a utxo is locked, the system spawns a goroutine waiting for a predefined expiration window before unlocking it if still locked to prevent locking utxos forever.
Since it might happen that the wallet is switched off while a utxo was locked, at every startup, the wallet checks if there utxos that can be directly unlocked or for which spawning goroutines waiting for the time left until lock expirtation.

Please @tiero, @louisinger  review this.

2022-03-21 17:05 UTC, altafan commented
> Shouldn't gen folder be at the base folder ie. api-spec/protobuf/gen and at same level be the protos api-spec/protobuf/ocean/v1 ?

I didn't changed this. `gen/` is indeed in the base folder, this branch is even with master at [this](https://github.com/vulpemventures/ocean/commit/e662f746586553d5eda0d4be22ba675f9ce6af44) commit, so should be all ok.

> Also we should add swagger support with Open API for JSON HTTP interface

Alright. I'm going to open a dedicated ticket as soon as this gets merged.

Note that, ideally, this PR wasn't expecting to make any change to api-spec (despite some bug fixing), but  in the meanwhile @louisinger and I agreed out-of-bound to drop the "account key" way of referencing a wallet account in favor of just its name.
The reason is that we want the system to pick a proper account derivation index for a new account, to prevent the client from choosing indexes of previously deleted accounts, for example.
From this, since a client works with account labels from the very beginning of their lifecycles, it's not likely it will prefer to identify them via their indexes later. There seems to be no advantage in adding such complexity on the ocean-wallet side. Account index, just like the account extended key, can just be retrieved as an account detail when getting wallet info.

2022-03-21 17:42 UTC, tiero commented on internal/core/application/account_service.go
> +		if spentUtxos := utxos[0].IsSpent(); spentUtxos {
why 0?

2022-03-22 10:17 UTC, tiero commented on internal/app-config/config.go
> +	}
nit: use a switch already to accomodate future impl?

2022-03-22 10:17 UTC, tiero commented on internal/app-config/config.go
> +	}
nit: use a switch already to accomodate future impl?

2022-03-22 10:59 UTC, tiero requested changes

2022-03-22 10:59 UTC, tiero commented on internal/core/domain/wallet.go
> +	MnemonicStore.Set(strMnemonic)
we storing the mnemonic clear text? should be encrypted (and retain master pub eventually)?

2022-03-22 10:59 UTC, tiero commented on internal/core/domain/wallet.go
> +func (w *Wallet) CreateAccount(name string) (*Account, error) {
This logic is tricky: now we assume an "account" matches the BIP44-esque account on the root path, when actually this is not true.

The meaning of account should be broader and be a dedicate space for a specific "script type/template" [Previous Discussion](https://github.com/vulpemventures/marina/issues/250#issuecomment-1062077859)

The conclusion we came is the following:


If a BIP that maps a script type to BIP32 derivation path (BIP49, BIP84, BIP48 etc..), then we should support it explicitly, otherwise we should create custom derivation that binds the account namespacing to it.





Now, we do not need to do this now (either soon), but to keep in mind, IMO we should have the following APIs


```hack
// increment bip44 account from the set root path
- CreateAccountBIP44("namespace")

// split/hash the namespace and use as derivation child(s)
- CreateAccountCustom("namespace")

2022-03-22 10:59 UTC, tiero commented on internal/core/domain/wallet.go
> +func (w *Wallet) CreateAccount(name string) (*Account, error) {
This logic is tricky: now we assume an "account" matches the BIP44-esque account on the root path, when actually this is not true.

The meaning of account should be broader and be a dedicate space for a specific "script type/template" [Previous Discussion](https://github.com/vulpemventures/marina/issues/250#issuecomment-1062077859)

The conclusion we came is the following:


If a BIP that maps a script type to BIP32 derivation path (BIP49, BIP84, BIP48 etc..), then we should support it explicitly, otherwise we should create custom derivation that binds the account namespacing to it.





Now, we do not need to do this now (either soon), but to keep in mind, IMO we should have the following APIs


```hack
// increment bip44 account from the set root path
- CreateAccountBIP44("namespace")

// split/hash the namespace and use as derivation child(s)
- CreateAccountCustom("namespace")

2022-03-22 11:00 UTC, tiero requested changes

2022-03-22 11:17 UTC, altafan commented on internal/core/application/account_service.go
> +		if spentUtxos := utxos[0].IsSpent(); spentUtxos {
I'll add a comment to the code to explain the reason. It's necessary indeed.

Anyway, the blockchain scanner, internally, is expected to receive some kind of report about "transactions of interest"  related to some watched address coming from mempool/blockchain.

`ports.BlockchainScanner`, by definition, exposes 2 channels (for utxos and txs) where the client app (in this case the account service) can listen to get notified about new/spent utxos/txs.

So basically it is up to the scanner to take a tx of interest, extract the "inputs of interest" and send them through the channel as spent utxos, and, similarly, extract and unblind the "outputs of interest" and send them through the channel as new utxos.

Therefore, the app listening to the neutrino's utxo channel receives a lit of either "spent utxos" representing  tx inputs or "new utxos" representing tx outputs. They are not mixed together. That's way it's enough to look only at the first utxo to infer the status of all utxos in the list.

2022-03-22 11:20 UTC, altafan commented on internal/core/domain/wallet.go
> +	MnemonicStore.Set(strMnemonic)
the mnemonic is stored encrypted on disk, while it is stored plaintext in memory when the wallet is unlocked.

Eventually, we can think about using the master xprv, not the xpu because we need to derive private keys for signing txs.

2022-03-22 11:24 UTC, altafan commented on internal/core/domain/wallet.go
> +func (w *Wallet) CreateAccount(name string) (*Account, error) {
Thank you for reporting this.

Btw, i didn't plan to have this feature in place now, we will open a ticket for that.

Then, do you think it's worth renaming the rpc in the proto `CreateAccountBip44` already?

2022-03-22 11:29 UTC, tiero commented on internal/core/domain/wallet.go
> +func (w *Wallet) CreateAccount(name string) (*Account, error) {
I would do that yeah

2022-03-22 12:17 UTC, altafan commented on internal/infrastructure/blockchain-scanner/neutrino/scanner.go
> +		txHex, _ := tx.ToHex()
because we can assume the transactions sent by the node are all correct.

2022-03-22 12:30 UTC, tiero commented on internal/infrastructure/blockchain-scanner/neutrino/service.go
> +		url := fmt.Sprintf("%s/tx/%s", baseUrl, key.TxID)
this looks like getting txs, not utxos...

2022-03-22 13:00 UTC, altafan commented on internal/infrastructure/blockchain-scanner/neutrino/service.go
> +		url := fmt.Sprintf("%s/tx/%s", baseUrl, key.TxID)
yes, for each requested utxo, we retrieve the tx and then parse the i-th output as a *domain.Utxo. 

Consider that while the GetUtxos method is here to stay, its implementation might be temporary. Is it correct to say that we should query the embedded node for this rather than esplora?

2022-03-22 15:11 UTC, tiero commented on internal/infrastructure/blockchain-scanner/neutrino/service.go
> +		url := fmt.Sprintf("%s/tx/%s", baseUrl, key.TxID)
well to do that we should keep indexes to fast lookup descriptor -> utxos, which can def be something we need a wallet tracking logic (derive N addresses, watch for activity, consume events and create indexes locally for it)

2022-03-22 20:58 UTC, tiero commented on api-spec/protobuf/ocean/v1alpha/wallet.proto
> +  // starting block for the wallet rescan.
```suggestion
  // starting block for the wallet rescan.
  // If not given, will rescan from genesis block
```

2022-03-22 21:55 UTC, altafan commented on api-spec/protobuf/ocean/v1alpha/wallet.proto
> +  // starting block for the wallet rescan.
the real genesis block or the wallet genesis block, like the blocktime stamp of the beta release?

2022-03-22 22:12 UTC, tiero commented on api-spec/protobuf/ocean/v1alpha/wallet.proto
> +  // starting block for the wallet rescan.
Well ideally ocean could work for any seed created with any software that uses BIP84 (or any other really), so here does not make sense to force users to use seed generated ONLY with ocean

2022-03-22 22:13 UTC, altafan commented on api-spec/protobuf/ocean/v1alpha/wallet.proto
> +  // starting block for the wallet rescan.
good point.

2022-04-26 12:51 UTC, altafan commented
@tiero this [commit](https://github.com/vulpemventures/ocean/pull/11/commits/87be71ccccda69efa83ad71588b043980921e285) should fix the issue raised on [taxi-daemon](https://github.com/vulpemventures/taxi-daemon/pull/96#discussion_r855288813).

2022-05-27 11:07 UTC, tiero commented on .goreleaser.yml
> +      ]
```suggestion
```

2022-05-27 11:07 UTC, tiero commented on .github/workflows/release.yml
> +          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
```suggestion
```

2022-08-05 12:17 UTC, altafan commented
Moved proto version from `v1alpha` to `v1`.

2022-08-16 16:24 UTC, merged