Wallet recovery
vulpemventures/ocean pull request #22
Opened 2022-10-13 14:09 UTC by sekulicd

This adds recovery method that is supposed to return utxos for x number of accounts.

@tiero @altafan please review.

2022-10-13 14:33 UTC, altafan commented on internal/core/application/wallet_service.go
> +			//we would need to refactor scanner in order to know if scanning is done
Actually, the scanner never finishes scanning an address because it can still be re-used in the future.  When an address is derived, it should be (and is) watched forever. And I'm not so keen to give every account restoration a window of time to consider the process completed.

I'm still uncertain about using the current scanner APIs for restoring. But I for sure agree with you that here, at app level, we need to know when a scanner finishes restoring an address or account.

What kind of refactor are you thinking to for the scanner?

An alternative solution that doesn't involve a refacotr could be adding a new `RestoreAccount` API that abstracts all the work for discovering account's addresses and utxos. With this kind od API, here we should just handle the results and stop the restoring after we find X (`2`?) consecutive empty accounts (ie. no utxos/txs found for any address)

2022-10-13 14:37 UTC, altafan commented on internal/core/application/wallet_service.go
> +	numOfAccounts int,
I do think it's part of our job to discover the accounts to restore, therefore I think the right approach should be to keep attempting to restore accounts until a certain consecutive number of them are found empty.

2022-10-13 14:40 UTC, altafan commented on internal/core/application/wallet_service.go
> +	recoveryWindow int,
maybe we don't need this? maybe we can use only `numOfAddressesPerAccount` (could be renamed `addressGapLimit`?

The idea is: I derive let's say the first 20 addresses, and I keep doing it until I don't find 20 consecutive unused addresses .

2022-10-13 15:38 UTC, sekulicd commented
Ok, i think i have better idea, to search directly in filters repo.
Check SearchTransactionsForOutputScripts method.

@tiero @altafan

2022-10-14 14:18 UTC, sekulicd commented
@tiero @altafan please check [restore](https://github.com/sekulicd/ocean/blob/24dcab1d6d5bc3bce7311244c1cb7db6d2c4f2eb/internal/core/application/wallet_service.go#L173) method which is fetching txs in sync mode based on filter/header repo.

2022-10-18 12:59 UTC, altafan requested changes

2022-10-18 12:59 UTC, altafan commented on internal/infrastructure/blockchain-scanner/elements/service.go
> +				break
can you explain this `break`?

2022-10-18 16:29 UTC, sekulicd commented on internal/config/config.go
> +	RestoreWalletNumOfAddressesPerAccountKey = "RESTORE_WALLET_NUM_OF_ADDRESSES_PER_ACCOUNT"
Done

2022-10-18 16:29 UTC, sekulicd commented on internal/core/application/wallet_service.go
>  	}
Done

2022-10-18 16:29 UTC, sekulicd commented on internal/core/application/wallet_service.go
> +	}
Done

2022-10-18 16:29 UTC, sekulicd commented on internal/core/application/wallet_service.go
> +		accountName := strconv.Itoa(accountCounter)
Done

2022-10-18 16:29 UTC, sekulicd commented on internal/core/application/wallet_service.go
> +		internalAddrNotFoundDelta += addressLoopCount*numOfAddressesPerAccount - chainLastIndex[domain.InternalChain]
Done

2022-10-18 16:29 UTC, sekulicd commented on internal/infrastructure/blockchain-scanner/elements/service.go
> +				break
Removed

2022-10-18 16:29 UTC, sekulicd commented on cmd/ocean/wallet.go
> +	walletRestoreCmd.MarkFlagRequired("birthday-block-hash")
Done

2022-11-11 12:28 UTC, altafan commented
@sekulicd i'm testing the restoration of this mnemonic:
```
tell worth behave moon duty file alien bacon design element attract era enter turtle cycle foot bone sand elevator useless release affair giggle engage
```

with this wallet configuration:
```
OCEAN_NETWORK=testnet
OCEAN_LOG_LEVEL=5
OCEAN_NO_TLS=true
OCEAN_STATS_INTERVAL=120
OCEAN_ESPLORA_URL=https://blockstream.info/liquidtestnet/api
OCEAN_NODE_RPC_ADDR=http://admin1:123@liquid-testnet.sevenlabs.dev:18884
OCEAN_UTXO_EXPIRY_DURATION_IN_SECONDS=240
```

Since the ocean service doesn't print any log within the process, it's hard to say what's going on but after 5+ mins it's still ongoing.

Also, since restoration can be a long process, we should define the RestoreWallet as server-side rpc instead of unary to make sure the connection doesn't timeout client-side (we'll do the same in another PR for InitWallet).

2022-11-14 10:44 UTC, sekulicd commented
> Since the ocean service doesn't print any log within the process, it's hard to say what's going on but after 5+ mins it's still ongoing. Can you try replicate this?

I added some logs.
Issue is that we are scanning from block_height=0, the tip is 606522 (in the moment of writing) and for each block we have 3 rpc calls(network latency):
L211 -> elements/service.go -> s.headersRepo.GetBlockHashByHeight
L295 -> elements/service.go -> s.filtersRepo.GetFilter
L247 -> elements/service.go -> s.headersRepo.ChainTip
So this is going really slow. I think we need to use Neutrino to sync full chain and only then ti start Ocean otherwise recovery will be to slow.
Also we are currently passing only 150 scripts to FindTransactionsForOutputScripts method, we should definitely increase this number to few thousands.

2022-12-13 15:59 UTC, sekulicd commented
> > Since the ocean service doesn't print any log within the process, it's hard to say what's going on but after 5+ mins it's still ongoing. Can you try replicate this?
> 
> I added some logs. Issue is that we are scanning from block_height=0, the tip is 606522 (in the moment of writing) and for each block we have 3 rpc calls(network latency): L211 -> elements/service.go -> s.headersRepo.GetBlockHashByHeight L295 -> elements/service.go -> s.filtersRepo.GetFilter L247 -> elements/service.go -> s.headersRepo.ChainTip So this is going really slow. I think we need to use Neutrino to sync full chain and only then ti start Ocean otherwise recovery will be to slow. Also we are currently passing only 150 scripts to FindTransactionsForOutputScripts method, we should definitely increase this number to few thousands.

@tiero @altafan how do we proceed with this?

2022-12-13 21:39 UTC, tiero commented
Let's supersede this in favor of using Electrum JSONRPC over TCP. Bonus is TCP batching compared to the REST HTTP Esplora interface

https://github.com/vulpemventures/ocean/issues/25

2023-01-25 18:37 UTC, altafan commented
Closing in favor of #43.

2023-01-25 18:37 UTC, closed without merging