Add low level rpc to sign taproot inputs
vulpemventures/ocean pull request #61
Opened 2023-12-15 16:33 UTC by altafan

This adds a low level rpc `SignPsetWithSchnorrKey` that accepts and signs a partial tx.

This pset must contain the account(s) xpub as global field and each taproot input to be signed must specify a TapBip32Derivation field.

Internally, the app service retrieves the account index for a global xpub and contrcuts the derivation path required by the signing wallet to generate the correct private key.

Please @louisinger review.

2023-12-15 16:42 UTC, tiero commented
I would add a test to serve as reference/example on how to use the API

2023-12-15 17:15 UTC, louisinger requested changes

2023-12-15 17:15 UTC, louisinger commented on pkg/wallet/single-sig/sign.go
> +		if err := signer.AddInSighashType(inIndex, sighashType); err != nil {
unnecessary if `sighashType` is SIGHASH_DEFAULT

2023-12-15 17:15 UTC, louisinger commented on pkg/wallet/single-sig/sign.go
> +		// If there are no leaf hashes, sign as keypath
it looks like key-path case is missing ?

2023-12-15 17:15 UTC, louisinger commented on pkg/wallet/single-sig/sign.go
> +			Signature: signature.Serialize(),
schnorr signatures include the input sighash at the end of the slice **only if** it's not `SIGHASH_DEFAULT`

2023-12-18 11:54 UTC, altafan commented on pkg/wallet/single-sig/sign.go
> +		// If there are no leaf hashes, sign as keypath
key path should be line 369-383

2023-12-18 14:21 UTC, louisinger approved these changes

2023-12-19 23:40 UTC, louisinger commented on pkg/wallet/single-sig/sign.go
> +	hashForSignature := unsignedTx.HashForWitnessV1(
`prevoutScripts`, `prevoutAssets` & `prevoutValues` must include **all the transaction inputs data** (not only the signed one)

2023-12-20 00:15 UTC, louisinger commented on pkg/wallet/single-sig/sign.go
> +	hashForSignature := unsignedTx.HashForWitnessV1(
also, EplicitAsset & ExplicitValue can't be used. The witness utxo data must be used, see the changes there: https://github.com/altafan/ocean/pull/2

2024-01-30 16:06 UTC, louisinger approved these changes

2024-01-30 17:10 UTC, merged