Fallback to esplora to fetch confirmation info for external txs
vulpemventures/ocean pull request #82
Opened 2024-02-02 14:45 UTC by altafan

This adds fallback strategy to esplora to fetch confirmation info of tx external to the wallet, ie not stored in the storage but fetched via blockchain scanner.

Unfortunately, there's no way we can use electrum's apis to get such info, so we have to fallback to esplora. For this, the usage of ESPLORA_URL env var has been revamped like follows:

By default, the esplora URL is derived from the network, but it can be customized at will by specifying it with `OCEAN_ESPLORA_URL`. This way, ocean can be served  in a dockerized env, like for example nigiri where the esplora URL becomes <container_name>:3001 instead of localhost.

Please @louisinger review.

2024-02-02 15:20 UTC, tiero requested changes

2024-02-02 15:20 UTC, tiero commented on internal/core/application/transaction_service.go
> +func (ts *TransactionService) fetchTxConfirmationDetails(txid string) (*domain.UtxoStatus, error) {
I see this as short term hack, but wouldn't be better to use get history via Electrum? Just to have a single dependency on the data-source. Under the hood Esplora does all with Electrum data

2024-02-02 15:59 UTC, altafan commented on internal/core/application/transaction_service.go
> +func (ts *TransactionService) fetchTxConfirmationDetails(txid string) (*domain.UtxoStatus, error) {
to get the tx history we should: fetch the txhex and decode the it, get the history for one of the output scripts, filter the history to select the tx of interest, eventually fetch the blockheader in case the tx is confirmed to return the confirmation info.

I don't like this solution either, but none of these workarounds would be needed at all if Blockstream/electrs supported returning [verbose info for a tx](https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-transaction-get). I don't expect this to be fixed soon unfortunately.

Maybe using electrum as described above is better than requiring another external service.

2024-02-02 16:46 UTC, altafan commented on internal/core/application/transaction_service.go
> +func (ts *TransactionService) fetchTxConfirmationDetails(txid string) (*domain.UtxoStatus, error) {
Update: I made the changes as described above and therefore I got rid of esplora but I'm seeing now a downside of using electrum only.

In case the tx is a coinbase one ([example](https://blockstream.info/liquidtestnet/tx/f7dd4272fff3a15214c18fc3f8bc7efe39d98c54d7a50bcc993e879602eaa710)) or in general it contains only non-common outputs scripts like OP_RETURN ([example](https://blockstream.info/liquidtestnet/tx/51a18c2f8442b6c6dc4e7afe53070f5cec89f5f887d67a509b0d391aec484f6e)), it's impossible to know the confirmation info because there's no valid script for which getting the history.

2024-02-02 16:48 UTC, altafan commented on internal/core/application/transaction_service.go
> +func (ts *TransactionService) fetchTxConfirmationDetails(txid string) (*domain.UtxoStatus, error) {
This means that even with these changes, clients should be aware that tx confirmation info might not be returned and they have to fallback to some plan B if that info is really needed.

2024-02-02 16:53 UTC, altafan commented on internal/core/application/transaction_service.go
> +func (ts *TransactionService) fetchTxConfirmationDetails(txid string) (*domain.UtxoStatus, error) {
By using esplora, instead, we have the certainty that the confirmation info are returned and therefore clients don't need to worry about the response missing this detail anymore.

2024-02-03 11:40 UTC, louisinger approved these changes
tACK

2024-02-06 18:43 UTC, tiero commented
utACK

2024-02-07 13:29 UTC, louisinger approved these changes

2024-02-08 05:50 UTC, merged